//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace languageSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class UslugaClient
    {
        public int ID_Uslugi { get; set; }
        public string UslName { get; set; }
        public System.DateTime TimeStart { get; set; }
        public string Client { get; set; }
    }
}
